webtalk_init -webtalk_dir D:/Projet_VHDL_MHAH_thermo/Projet_VHDL_MHAH_thermo.sim/sim_1/behav/xsim/xsim.dir/write_8b_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 14 09:54:02 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174131902_174131903_210671458_965" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "66d09ee0-8b3c-4d85-bd96-139a9324f1de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c0ccedc5263e4a0d91001d16eeb5c224" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14488_KB" -context "xsim\\usage"
webtalk_transmit -clientid 35441264 -regid "174131902_174131903_210671458_965" -xml D:/Projet_VHDL_MHAH_thermo/Projet_VHDL_MHAH_thermo.sim/sim_1/behav/xsim/xsim.dir/write_8b_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Projet_VHDL_MHAH_thermo/Projet_VHDL_MHAH_thermo.sim/sim_1/behav/xsim/xsim.dir/write_8b_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projet_VHDL_MHAH_thermo/Projet_VHDL_MHAH_thermo.sim/sim_1/behav/xsim/xsim.dir/write_8b_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
